"use client"

import type { CSSProperties, ReactNode } from 'react'
import { useEffect, useMemo, useRef, useState } from 'react'
import { useCompanyProfile, type CompanyProfile } from '@/hooks/useCompanyProfile'
import { CompanyLogo } from './CompanyLogo'

const shell: CSSProperties = { background: '#f7f8f6', padding: 16, borderRadius: 18, border: '1px solid #e7e9e2' }
const card: CSSProperties = { background: '#fff', border: '1px solid #e5e7de', borderRadius: 14, overflow: 'hidden' }
const titleBar: CSSProperties = { fontSize: 11, fontWeight: 800, color: '#64706a', padding: '10px 14px', borderBottom: '1px solid #e5e7de', background: '#f4f6f2', textTransform: 'uppercase', letterSpacing: '.05em' }
const input: CSSProperties = { width: '100%', fontSize: 12, border: '1px solid #d5ddd7', borderRadius: 6, padding: '7px 9px', background: '#fff', color: '#1f2933' }
const btn: CSSProperties = { fontSize: 11, padding: '7px 14px', borderRadius: 8, border: '1px solid #d5ddd7', background: '#fff', color: '#1f2933', cursor: 'pointer', fontWeight: 700 }
const primaryBtn: CSSProperties = { ...btn, background: '#1D9E75', borderColor: '#1D9E75', color: '#fff' }
function Field({ label, children, full }: { label: string; children: ReactNode; full?: boolean }) { return <label style={{ padding: '10px 14px', borderBottom: '1px solid #e5e7de', borderRight: full ? 'none' : '1px solid #e5e7de', gridColumn: full ? '1 / -1' : undefined }}><div style={{ fontSize: 10, color: '#6b7280', marginBottom: 5, fontWeight: 700 }}>{label}</div>{children}</label> }

export function CompanyBrandingView() {
  const { profile, saving, error, saveProfile, uploadLogo, removeLogo } = useCompanyProfile()
  const [form, setForm] = useState<CompanyProfile>(profile)
  const [message, setMessage] = useState('')
  const inputRef = useRef<HTMLInputElement | null>(null)
  useEffect(() => setForm(profile), [profile])
  const letter = useMemo(() => (form.company_name || 'B').trim().charAt(0).toUpperCase() || 'B', [form.company_name])
  const update = (patch: Partial<CompanyProfile>) => setForm((prev) => ({ ...prev, ...patch }))
  async function save() { const res = await saveProfile(form); setMessage(res.storedIn === 'supabase' ? 'Company profile saved to Supabase.' : 'Saved locally. Supabase company_profile table/storage can be connected later.') }
  async function onLogoFile(file?: File | null) { if (!file) return; const res = await uploadLogo(file); setForm((prev) => ({ ...prev, logo_url: res.url })); setMessage(res.storedIn === 'supabase' ? 'Logo uploaded to Supabase Storage.' : 'Logo preview saved locally because Supabase Storage is not configured yet.') }
  return <div style={shell}>
    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14, gap: 12, flexWrap: 'wrap' }}><div><div style={{ fontSize: 18, fontWeight: 800, color: '#1f2933' }}>Company Branding & Profile</div><div style={{ fontSize: 12, color: '#667085', marginTop: 2 }}>Settings → Company Branding · logo upload, report header and PDF footer preview</div></div><button style={primaryBtn} onClick={save} disabled={saving}>{saving ? 'Saving…' : 'Save Changes'}</button></div>
    {(message || error) && <div style={{ marginBottom: 12, padding: '9px 12px', borderRadius: 10, border: `1px solid ${error ? '#f5c2c2' : '#bfe7d8'}`, background: error ? '#fff3f3' : '#edf9f3', color: error ? '#a32d2d' : '#0f6e56', fontSize: 12 }}>{message || 'Fallback mode active.'}{error ? ` (${error})` : ''}</div>}
    <div style={{ display: 'grid', gridTemplateColumns: 'minmax(320px, 1fr) 300px', gap: 12 }}>
      <div><div style={card}><div style={titleBar}>Company Logo</div><div style={{ margin: 14, border: '1.5px dashed #cdd6d1', borderRadius: 12, padding: 24, textAlign: 'center', background: '#f7faf8' }}><div style={{ width: 78, height: 78, borderRadius: 13, background: form.logo_url ? '#fff' : '#1D9E75', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 10px', color: '#fff', fontSize: 22, fontWeight: 800, overflow: 'hidden', border: form.logo_url ? '1px solid #e5e7de' : 'none' }}>{form.logo_url ? <img src={form.logo_url} alt="Company logo" style={{ width: '100%', height: '100%', objectFit: 'contain' }} /> : letter}</div><div style={{ fontSize: 13, fontWeight: 800, color: '#1f2933' }}>{form.company_name || 'BuildCore ERP'}</div><div style={{ fontSize: 10, color: '#667085', margin: '4px 0 12px' }}>Upload to Supabase Storage when available; local fallback otherwise.</div><input ref={inputRef} type="file" accept="image/*" style={{ display: 'none' }} onChange={(e) => void onLogoFile(e.target.files?.[0])} /><button style={btn} onClick={() => inputRef.current?.click()}>Upload New Logo</button><button style={{ ...btn, marginLeft: 6 }} onClick={async () => { await removeLogo(); setForm((p) => ({ ...p, logo_url: null })); setMessage('Logo removed from profile fallback.') }}>Remove</button></div><div style={{ padding: '10px 14px', borderTop: '1px solid #e5e7de' }}><div style={{ fontSize: 10, color: '#667085', marginBottom: 5, fontWeight: 700 }}>Logo URL fallback</div><input style={input} value={form.logo_url ?? ''} placeholder="/assets/logo.png" onChange={(e) => update({ logo_url: e.target.value || null })} /></div></div>
        <div style={{ ...card, marginTop: 10 }}><div style={titleBar}>Company Information</div><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr' }}><Field label="Company Name (English)"><input style={input} value={form.company_name} onChange={(e) => update({ company_name: e.target.value })} /></Field><Field label="Company Name (Arabic)"><input style={input} dir="rtl" value={form.company_name_ar ?? ''} onChange={(e) => update({ company_name_ar: e.target.value })} /></Field><Field label="Phone"><input style={input} value={form.phone ?? ''} onChange={(e) => update({ phone: e.target.value })} /></Field><Field label="Email"><input style={input} value={form.email ?? ''} onChange={(e) => update({ email: e.target.value })} /></Field><Field label="Address" full><input style={input} value={form.address ?? ''} onChange={(e) => update({ address: e.target.value })} /></Field><Field label="Tax / VAT Registration No"><input style={input} value={form.tax_number ?? ''} onChange={(e) => update({ tax_number: e.target.value })} /></Field><Field label="Commercial Register No"><input style={input} value={form.commercial_register ?? ''} onChange={(e) => update({ commercial_register: e.target.value })} /></Field><Field label="PDF Footer Text" full><input style={input} value={form.pdf_footer ?? ''} onChange={(e) => update({ pdf_footer: e.target.value })} /></Field></div></div></div>
      <div style={card}><div style={{ ...titleBar, borderBottom: 'none' }}>Live Preview</div><div style={{ padding: '0 14px 14px' }}><div style={{ background: '#f4f6f2', border: '1px solid #e5e7de', borderRadius: 10, padding: 12, marginBottom: 10 }}><CompanyLogo profile={form} size={30} showName variant="sidebar" /><div style={{ fontSize: 10, color: '#7b847e', marginTop: 8 }}>Sidebar / header appearance</div></div><div style={{ border: '1px solid #e5e7de', borderRadius: 10, padding: 12, background: '#f7f8f6' }}><div style={{ display: 'flex', alignItems: 'center', gap: 10, paddingBottom: 10, borderBottom: '1px solid #e5e7de', marginBottom: 10 }}><CompanyLogo profile={form} size={42} showName={false} variant="pdf" /><div><div style={{ fontSize: 12, fontWeight: 800, color: '#1f2933' }}>{form.company_name}</div><div style={{ fontSize: 9, color: '#667085' }}>{form.address || 'Company address'} · {form.phone || 'Phone'}</div><div style={{ fontSize: 9, color: '#667085' }}>VAT: {form.tax_number || 'Tax / VAT No'}</div></div></div><div style={{ fontSize: 11, color: '#667085', fontWeight: 800 }}>Subcontractor Payment Certificate</div><div style={{ marginTop: 10, height: 46, background: '#edf0ea', borderRadius: 8 }} /><div style={{ marginTop: 10, paddingTop: 8, borderTop: '1px solid #e5e7de', fontSize: 9, color: '#8b938f', textAlign: 'center' }}>{form.pdf_footer || 'ERP generated document footer'}</div></div><div style={{ marginTop: 12 }}><div style={{ fontSize: 10, color: '#667085', marginBottom: 8, fontWeight: 800 }}>Logo appears in:</div><div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>{['Login page','Home page','Sidebar','PDF Preview','Reports','Dashboards'].map((x) => <span key={x} style={{ fontSize: 10, padding: '3px 10px', borderRadius: 999, background: '#e6f1fb', color: '#185fa5', fontWeight: 700 }}>{x}</span>)}</div></div></div></div>
    </div>
  </div>
}
